# Author: Nuno Aguiar
help:
  text   : GitHub step to delete extra build files and capture the version.
  expects:
  - name     : path
    desc     : The build output
    mandatory: true

todo:
- Clean up and get version

ojob:
  opacks      :
  - openaf: 20230704
  catch       : printErrnl("[" + job.name + "] "); if (isDef(exception.javaException)) exception.javaException.printStackTrace(); else printErr(exception)
  logToConsole: true   # to change when finished


jobs:
# -------------------------------
- name : Clean up and get version
  check:
    in:
      path: isString
  exec : |
    var remove = [], versions = {}

    io.listFiles(args.path).files.forEach(f => {
      var _p = f.filename.match(/((\d\.?)+)$/)
      if (_p) {
        versions[_p[0]]= 1
      } else {
        remove.push(f)
      }
    })

    remove.forEach(f => {
      //tlog("Deleting {{filename}}...", f)
      //io.rm(f.canonicalPath)
    })

    var version = $from(Object.keys(versions).map(r=>({v:r}))).attach("l", r => r.v.length).sort("l").at(0).v
    log("Adding version=" + version + " in '" + getEnv("GITHUB_OUTPUT") + "'...")
    io.writeFileString("version=" + version, getEnv("GITHUB_OUTPUT"), __, true)