name: Builds

on  :
  ## Comment the entries below you won't be needing
  #  (and double-check if you repo uses 'main' or 'master')
  #push        :
    #branches:
    #- main
    #paths:
    #- 'xyz/**'
    #paths-ignore:
    #- '.github/**'
  #pull_request:
    #branches:
    #- main
    #paths:
    #- 'xyz/**'
    #paths-ignore:
    #- '.github/**'
  #schedule    :
  #- cron: '30 6 * * *'

  ## Uncomment and adapt the following lines to trigger the action upon complete of another
  ##
  #workflow_run:
  #  workflows:
  #    - 'main.yml'
  #  types:
  #    - completed

  workflow_dispatch:
  ## Uncomment the following lines if you need to provide specific inputs
  ##
  #  inputs:
  #    inputOne:
  #      description: 'Sample input to use'
  #      required   : true
  #      default    : 'some value'

jobs:
  # ============
  buildAlpineJE:
    runs-on: ubuntu-latest 
    permissions:
      contents     : write
      pull-requests: write

    steps  :
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    # --------------
    - name: Checkout
      uses: actions/checkout@v3

    # -----------
    - name: Build
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: build.yaml
        args: 'op=buildAlpineJE arch=amd64'
        dist: t8

    # --------------------
    - name: Upload output
      uses: actions/upload-artifact@v2
      with:
        name: libjemalloc_alpine_x64.tgz
        path: buildAlpineJE

  # ============
  buildAlpineTC:
    runs-on: ubuntu-latest 
    permissions:
      contents     : write
      pull-requests: write

    steps  :
    # --------------------------
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    # --------------
    - name: Checkout
      uses: actions/checkout@v3

    # -----------
    - name: Build
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: build.yaml
        args: 'op=buildAlpineTC arch=amd64'
        dist: t8

    # --------------------
    - name: Upload output
      uses: actions/upload-artifact@v2
      with:
        name: libtcmalloc_alpine_x64.tgz
        path: buildAlpineTC 
    
  # ================
  buildAlpineJE_ARM:
    runs-on: ubuntu-latest 
    permissions:
      contents     : write
      pull-requests: write

    steps  :
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    # --------------
    - name: Checkout
      uses: actions/checkout@v3

    # -----------
    - name: Build
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: build.yaml
        args: 'op=buildAlpineJE arch=arm64'
        dist: t8

    # --------------------
    - name: Upload output
      uses: actions/upload-artifact@v2
      with:
        name: libjemalloc_alpine_aarch64.tgz
        path: buildAlpineJE