name: Builds

on  :
  ## Comment the entries below you won't be needing
  #  (and double-check if you repo uses 'main' or 'master')
  #push        :
    #branches:
    #- main
    #paths:
    #- 'xyz/**'
    #paths-ignore:
    #- '.github/**'
  #pull_request:
    #branches:
    #- main
    #paths:
    #- 'xyz/**'
    #paths-ignore:
    #- '.github/**'
  #schedule    :
  #- cron: '30 6 * * *'

  ## Uncomment and adapt the following lines to trigger the action upon complete of another
  ##
  #workflow_run:
  #  workflows:
  #    - 'main.yml'
  #  types:
  #    - completed

  workflow_dispatch:
  ## Uncomment the following lines if you need to provide specific inputs
  ##
  #  inputs:
  #    inputOne:
  #      description: 'Sample input to use'
  #      required   : true
  #      default    : 'some value'

jobs:
  # ============
  buildAlpineJE:
    runs-on: ubuntu-latest 
    permissions:
      contents     : write
      pull-requests: write

    steps  :
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    # --------------
    - name: Checkout
      uses: actions/checkout@v3

    # -----------
    - name: Build
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: build.yaml
        args: 'op=buildAlpineJE arch=amd64'
        dist: t8

    # -----------------------
    - name: Clean and version
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: cleanAndVersion.yaml
        args: 'path=buildAlpineJE'
        dist: t8

    # -------------------
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: libjemalloc-${{ env.version }}_alpine_x64.tgz
        path: buildAlpineJE

  # ============
  buildAlpineTC:
    runs-on: ubuntu-latest 
    permissions:
      contents     : write
      pull-requests: write

    steps  :
    # --------------------------
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    # --------------
    - name: Checkout
      uses: actions/checkout@v3

    # -----------
    - name: Build
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: build.yaml
        args: 'op=buildAlpineTC arch=amd64'
        dist: t8

    # -----------------------
    - name: Clean and version
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: cleanAndVersion.yaml
        args: 'path=buildAlpineTC'
        dist: t8

    # --------------------
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: "libtcmalloc-${{ env.version }}_alpine_x64.tgz"
        path: buildAlpineTC 
    
  # ================
  buildOracle8JE:
    runs-on: ubuntu-latest 
    permissions:
      contents     : write
      pull-requests: write

    steps  :
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    # --------------
    - name: Checkout
      uses: actions/checkout@v3

    # -----------
    - name: Build
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: build.yaml
        args: 'op=buildOracle8JE'
        dist: t8

    # --------------------
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: libjemalloc-${{ env.version }}_oracle8_x64.tgz
        path: buildOracle8JE

  # ================
  buildOracle8TC:
    runs-on: ubuntu-latest 
    permissions:
      contents     : write
      pull-requests: write

    steps  :
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    # --------------
    - name: Checkout
      uses: actions/checkout@v3

    # -----------
    - name: Build
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: build.yaml
        args: 'op=buildOracle8TC'
        dist: t8

    # --------------------
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: libtcmalloc-${{ env.version }}_oracle8_x64.tgz
        path: buildOracle8TC

  # ================
  buildOracle9JE:
    runs-on: ubuntu-latest 
    permissions:
      contents     : write
      pull-requests: write

    steps  :
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    # --------------
    - name: Checkout
      uses: actions/checkout@v3

    # -----------
    - name: Build
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: build.yaml
        args: 'op=buildOracle9JE'
        dist: t8

    # --------------------
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: libjemalloc-${{ env.version }}_oracle9_x64.tgz
        path: buildOracle9JE

  # ================
  buildOracle9TC:
    runs-on: ubuntu-latest 
    permissions:
      contents     : write
      pull-requests: write

    steps  :
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    # --------------
    - name: Checkout
      uses: actions/checkout@v3

    # -----------
    - name: Build
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: build.yaml
        args: 'op=buildOracle9TC'
        dist: t8

    # --------------------
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: libtcmalloc-${{ env.version }}_oracle9_x64.tgz
        path: buildOracle9TC

  # ================
  buildUBI8JE:
    runs-on: ubuntu-latest 
    permissions:
      contents     : write
      pull-requests: write

    steps  :
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    # --------------
    - name: Checkout
      uses: actions/checkout@v3

    # -----------
    - name: Build
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: build.yaml
        args: 'op=buildUBI8JE'
        dist: t8

    # --------------------
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: libjemalloc-${{ env.version }}_ubi8_x64.tgz
        path: buildUBI8JE

  # ================
  buildUBI8TC:
    runs-on: ubuntu-latest 
    permissions:
      contents     : write
      pull-requests: write

    steps  :
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    # --------------
    - name: Checkout
      uses: actions/checkout@v3

    # -----------
    - name: Build
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: build.yaml
        args: 'op=buildUBI8TC'
        dist: t8

    # --------------------
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: libtcmalloc-${{ env.version }}_ubi8_x64.tgz
        path: buildUBI8TC

  # ================
  buildUBIJE:
    runs-on: ubuntu-latest 
    permissions:
      contents     : write
      pull-requests: write

    steps  :
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    # --------------
    - name: Checkout
      uses: actions/checkout@v3

    # -----------
    - name: Build
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: build.yaml
        args: 'op=buildUBIJE'
        dist: t8

    # --------------------
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: libjemalloc-${{ env.version }}_ubi9_x64.tgz
        path: buildUBIJE

  # ================
  buildUBITC:
    runs-on: ubuntu-latest 
    permissions:
      contents     : write
      pull-requests: write

    steps  :
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    # --------------
    - name: Checkout
      uses: actions/checkout@v3

    # -----------
    - name: Build
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: build.yaml
        args: 'op=buildUBITC'
        dist: t8

    # --------------------
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: libtcmalloc-${{ env.version }}_ubi9_x64.tgz
        path: buildUBITC



  # ============
  buildAlpineJEARM:
    runs-on: ubuntu-latest 
    permissions:
      contents     : write
      pull-requests: write

    steps  :
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    # --------------
    - name: Checkout
      uses: actions/checkout@v3
  
    # -----------------
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    # -----------
    - name: Build
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: build.yaml
        args: 'op=buildAlpineJE arch=arm64'
        dist: t8

    # -----------------------
    - name: Clean and version
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: cleanAndVersion.yaml
        args: 'path=buildAlpineJE'
        dist: t8

    # -------------------
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: libjemalloc-${{ env.version }}_alpine_aarch64.tgz
        path: buildAlpineJE

  # ============
  buildAlpineTCARM:
    runs-on: ubuntu-latest 
    permissions:
      contents     : write
      pull-requests: write

    steps  :
    # --------------------------
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    # --------------
    - name: Checkout
      uses: actions/checkout@v3

    # -----------------
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    # -----------
    - name: Build
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: build.yaml
        args: 'op=buildAlpineTC arch=arm64'
        dist: t8

    # -----------------------
    - name: Clean and version
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: cleanAndVersion.yaml
        args: 'path=buildAlpineTC'
        dist: t8

    # --------------------
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: "libtcmalloc-${{ env.version }}_alpine_aarch64.tgz"
        path: buildAlpineTC 
    
  # ================
  buildOracle8JEARM:
    runs-on: ubuntu-latest 
    permissions:
      contents     : write
      pull-requests: write

    steps  :
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    # --------------
    - name: Checkout
      uses: actions/checkout@v3

    # -----------------
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    # -----------
    - name: Build
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: build.yaml
        args: 'op=buildOracle8JE arch=arm64'
        dist: t8

    # --------------------
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: libjemalloc-${{ env.version }}_oracle8_aarch64.tgz
        path: buildOracle8JE

  # ================
  buildOracle8TCARM:
    runs-on: ubuntu-latest 
    permissions:
      contents     : write
      pull-requests: write

    steps  :
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    # --------------
    - name: Checkout
      uses: actions/checkout@v3

    # -----------------
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    # -----------
    - name: Build
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: build.yaml
        args: 'op=buildOracle8TC arch=arm64'
        dist: t8

    # --------------------
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: libtcmalloc-${{ env.version }}_oracle8_aarch64.tgz
        path: buildOracle8TC

  # ================
  buildOracle9JEARM:
    runs-on: ubuntu-latest 
    permissions:
      contents     : write
      pull-requests: write

    steps  :
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    # --------------
    - name: Checkout
      uses: actions/checkout@v3

    # -----------------
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    # -----------
    - name: Build
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: build.yaml
        args: 'op=buildOracle9JE arch=arm64'
        dist: t8

    # --------------------
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: libjemalloc-${{ env.version }}_oracle9_aarch64.tgz
        path: buildOracle9JE

  # ================
  buildOracle9TCARM:
    runs-on: ubuntu-latest 
    permissions:
      contents     : write
      pull-requests: write

    steps  :
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    # --------------
    - name: Checkout
      uses: actions/checkout@v3

    # -----------------
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    # -----------
    - name: Build
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: build.yaml
        args: 'op=buildOracle9TC arch=arm64'
        dist: t8

    # --------------------
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: libtcmalloc-${{ env.version }}_oracle9_aarch64.tgz
        path: buildOracle9TC

  # ================
  buildUBI8JEARM:
    runs-on: ubuntu-latest 
    permissions:
      contents     : write
      pull-requests: write

    steps  :
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    # --------------
    - name: Checkout
      uses: actions/checkout@v3

    # -----------------
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    # -----------
    - name: Build
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: build.yaml
        args: 'op=buildUBI8JE arch=arm64'
        dist: t8

    # --------------------
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: libjemalloc-${{ env.version }}_ubi8_aarch64.tgz
        path: buildUBI8JE

  # ================
  buildUBI8TCARM:
    runs-on: ubuntu-latest 
    permissions:
      contents     : write
      pull-requests: write

    steps  :
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    # --------------
    - name: Checkout
      uses: actions/checkout@v3

    # -----------------
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    # -----------
    - name: Build
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: build.yaml
        args: 'op=buildUBI8TC arch=arm64'
        dist: t8

    # --------------------
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: libtcmalloc-${{ env.version }}_ubi8_aarch64.tgz
        path: buildUBI8TC

  # ================
  buildUBIJEARM:
    runs-on: ubuntu-latest 
    permissions:
      contents     : write
      pull-requests: write

    steps  :
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    # --------------
    - name: Checkout
      uses: actions/checkout@v3

    # -----------------
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    # -----------
    - name: Build
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: build.yaml
        args: 'op=buildUBIJE arch=arm64'
        dist: t8

    # --------------------
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: libjemalloc-${{ env.version }}_ubi9_aarch64.tgz
        path: buildUBIJE

  # ================
  buildUBITCARM:
    runs-on: ubuntu-latest 
    permissions:
      contents     : write
      pull-requests: write

    steps  :
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    # --------------
    - name: Checkout
      uses: actions/checkout@v3

    # -----------------
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    # -----------
    - name: Build
      uses: openaf/ojob-action@v4
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: build.yaml
        args: 'op=buildUBITC arch=arm64'
        dist: t8

    # --------------------
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: libtcmalloc-${{ env.version }}_ubi9_aarch64.tgz
        path: buildUBITC

